spring:
  profiles:
    active: dev
  application:
    name: microservice-zuul-gateway
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    aigouEmployee.serviceId: employee-provider
    aigouEmployee.path: /employee/**
  ignored-services: "*" #忽略直接使用服务名访问
  prefix: /aigou  #访问前缀
